### ISSUE TITLE
Supported Python Version(s)

### ISSUE THREAD

**Issue by isurulucky** [Tractables/pyjuice#19]
Hi, 

I was trying out pyjuice 2.2.0 with python 3, and noted that it gives the below error for the train a pc example [1]. 

```
  TypeError: 'float' object cannot be interpreted as an integer
  File "pyjuice/src/pyjuice/layer/input_layer.py", line 947, in _compile_triton_kernel
    seed_str = f"_{random.randint(0,1e8)}"
                   ^^^^^^^^^^^^^^^^^^^^^
```

What is the compatible python version? Thanks in advance.

[1]. https://tractables.github.io/pyjuice/getting-started/tutorials/01_train_pc.html#sphx-glr-getting-started-tutorials-01-train-pc-py

**Comment by liuanji** [comment]
Hi isurulucky,

The problem seems to be that certain versions of python will interpret 1e8 as an integer and others will interpret it as a float. I [changed it](https://github.com/Tractables/pyjuice/commit/3686af44e194ac7edd1b5e1781793f68d5da6bbe) to int(1e8) and hopefully now it works for all python versions. Please try the latest main branch.

Best,
Anji

**Comment by isurulucky** [comment]
Hi Anji, 

Thanks for the prompt fix. I did the same locally (replacing 1e8 by 10^8), and got over this particular issue. However am now seeing some issues related to data conversions, which I suspect are related to triton. Will open a different issue to discuss. 

BR, 
Isuru
